Support Azure blob as source
AzureArcForKubernetes/azure-cli-extensions pull request #156
Opened 2022-07-29 21:26 UTC by summerhasama

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

2022-09-23 21:27 UTC, NarayanThiru requested changes

2022-09-28 19:33 UTC, bavneetsingh16 commented on src/k8s-configuration/azext_k8s_configuration/consts.py
> +    "Provide '--sp-client-id', '--sp-tenant-id', and one of '--sp-client-secret' or '--sp-client-cert'"
replace 'one of' with 'either'

2022-09-28 19:34 UTC, bavneetsingh16 commented on src/k8s-configuration/azext_k8s_configuration/consts.py
> +    "Provide only one of '--sp-client-secret' or '--sp-client-cert'"
replace with 'either'

2022-09-28 19:36 UTC, bavneetsingh16 commented on src/k8s-configuration/azext_k8s_configuration/consts.py
> +    "Error! Too many authentication methods for Azure Blob"
'provided'

2022-09-28 19:38 UTC, bavneetsingh16 commented on src/k8s-configuration/azext_k8s_configuration/consts.py
> +    "Specify one authentication method of '--local-auth-ref', '--account-key', '--sas-token', '--mi-client-id', or service principal with '--sp-client-id', '--sp-tenant-id', and one of '--sp-client-s
Specify one of the available authentication methods from the list:

2022-09-28 21:31 UTC, bavneetsingh16 commented on src/k8s-configuration/azext_k8s_configuration/_params.py
> +            help="Name of the Azure Blob Storage container to sync",
got it reviewed

2022-09-28 21:31 UTC, bavneetsingh16 commented on src/k8s-configuration/azext_k8s_configuration/consts.py
> +REQUIRED_AZURE_BLOB_SERVICE_PRINCIPAL_VALUES_MISSING_ERROR = (
got it reviewed and made changes as suggested

2022-09-29 00:30 UTC, NarayanThiru approved these changes

2022-09-29 00:30 UTC, merged